### ISSUE TITLE
Unable to download mod from CurseForge

### ISSUE THREAD

**Issue by blueyu2** [covers1624/LegacyFarms#1]
Attempting to download the file from CurseForge results in a 404 error. This is probably due to the mod file being named "legacyfarms-1.0-#30.jar". The '#' confuses the CurseForge server, causing it to request http://addons-origin.cursecdn.com:80/files/2273/528/legacyfarms-1.0- instead of http://addons-origin.cursecdn.com:80/files/2273/528/legacyfarms-1.0-#30.jar.

This issue can be resolved by removing the '#' from the file name.

**Comment by covers1624** [comment]
hmm interesting, here is the jenkins for now http://adel.podgeweb.com:8080/

**Comment by covers1624** [comment]
Fixed, download on curse.
