### ISSUE TITLE
LoaderException error when loading game

### ISSUE THREAD

**Issue by Staegrin** [covers1624/LegacyFarms#3]
Added the mod to my modlist. Had a crash during starting the game

crashlog:
http://pastebin.com/Euh11vV8
fml-client-latest:
https://gist.github.com/Staegrin/50661061cbca99fd5ff0

**Comment by covers1624** [comment]
Do you have any forestry modules disabled?

**Comment by Staegrin** [comment]
Apiculture
aboriculture
lepidopterology
mail
propolis.pipe
are all turned off (false)

**Comment by covers1624** [comment]
In the current build Apiculture and Arboriculture are required to be enabled. i will work on legacy farms not crashing if they are not enabled.

**Comment by Staegrin** [comment]
Correct, with Apiculture and Arboriculture turned on the game loads fine.
